name: CI Workflow

on:
  push:
    branches:
      - main  # ou 'master', ou toute autre branche à surveiller
  pull_request:
    branches:
      - main 

jobs:
  test-and-quality:
    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black  # Ajouter Black aux dépendances
        
    - name: Run Black for code formatting
      run: |
        black src/  # Reformater automatiquement le code du dossier 'src'

    - name: Run tests with pytest
      run: |
        pytest tests/

    - name: Run flake8 for code quality
      run: |
        flake8 src/  # Vérifier la qualité du code dans le dossier 'src'
